TRUNCATE TABLE content RESTART IDENTITY;
TRUNCATE TABLE emails RESTART IDENTITY;
TRUNCATE TABLE passwords RESTART IDENTITY;
TRUNCATE TABLE password_reset_tokens RESTART IDENTITY;
TRUNCATE TABLE api_tokens RESTART IDENTITY;